<?php
$z[0]=Array("typename","",4,21);
$z[0][4]=array();
$z[1]=Array("typeurl","",35,51);
$z[1][4]=array();
$z[2]=Array("arcurl","",125,140);
$z[2][4]=array();
$z[3]=Array("litpic","",152,167);
$z[3][4]=array();
$z[4]=Array("title","",174,188);
$z[4][4]=array();
$z[5]=Array("title","",199,213);
$z[5][4]=array();
$z[6]=Array("description","",220,270);
$z[6][4]=array();
$z[6][4]['function']="cn_substr(@me,110)";

?>