<?php
$z[0]=Array("csz","",19,60);
$z[0][4]=array();
$z[0][4]['function']="cn_substr(@me,10)";
$z[1]=Array("bmbh","",78,120);
$z[1][4]=array();
$z[1][4]['function']="cn_substr(@me,16)";
$z[2]=Array("s_province","",145,164);
$z[2][4]=array();
$z[3]=Array("caiyi","",184,227);
$z[3][4]=array();
$z[3][4]['function']="cn_substr(@me,12)";
$z[4]=Array("pubdate","",236,283);
$z[4][4]=array();
$z[4][4]['function']="MyDate('Y-m-d',@me)";

?>