
<field:frxm itemname="姓名" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:frxm>

<field:mz itemname="民族" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:mz>

<field:bianhao itemname="编号" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:bianhao>

<field:zzmm itemname="政治面貌" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zzmm>



<field:dqps itemname="当前投票数" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:dqps>

<field:zwpj itemname="自我评价" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zwpj>

<field:shipin itemname="个人视频" autofield="1" notsend="0" type="media" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:shipin>


