
<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:dwmc itemname="单位名称" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dwmc>

<field:gszw itemname="公司职位" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:gszw>

<field:jmqy itemname="加盟区域" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:jmqy>

<field:tel itemname="联系电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel>

<field:lemail itemname="联系邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:lemail>
