<div class="list_box pc">
       <span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span>      
       <a href="[field:arcurl/]"><p>[field:description function='cn_substr(@me,200)'/]</p><h2>【[field:title/]】</h2></a>
    </div>
     <a href="article_article.html" class="mcss">
      <div class="mlist_boxl"><img src="[field:litpic/]"></div>
      <div class="mlist_boxr"><h2[field:title/]</h2>
      <p>[field:description function='cn_substr(@me,250)'/]</p></div>
      </a>