会员头像：<a href="[field:spaceurl /]" class="userface"><img src="[field:face/]" width="52" height="52" /></a>
        会员用户名：<a href=’[field:spaceurl /]‘ class="username">[field:uname/]</a>
        会员详细资料：<a href="[field:spaceurl /]" class="useract-vi">查看详细资料</a>
        给他留言：<a href="[field:spaceurl /]&action=guestbook" class="useract-pm">发送留言</a>
        加为好友：<a href="[field:spaceurl /]&action=newfriend" class="useract-af">加为好友</a>
        用户等级:[field:rankname /]
        注册时间:[field:jointime function="MyDate('Y-m-d H:m',@me)"/]
        最后登录:[field:logintime function="MyDate('Y-m-d H:m',@me)"/]