
<field:time itemname="时长" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:time>

<field:neir itemname="内容" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:neir>

<field:feiy itemname="费用" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:feiy>

<field:price itemname="价格" autofield="1" notsend="0" type="float" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:price>

<field:phone itemname="电话" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="15" page="">
</field:phone>

<field:teacher itemname="导师" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="20" page="">
</field:teacher>

<field:buycount itemname="已购买次数" autofield="1" notsend="0" type="int" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:buycount>

