<?php
$z[0]=Array("flink","",34,56);
$z[0][4]=array();
$z[0][4]['row']="24";
$z[1]=Array("channel","\r\n <li><a href=\"[field:typelink/]\" rel=\"nofollow\"> [field:typename/] </a></li>\r\n",178,375);
$z[1][4]=array();
$z[1][4]['type']="top";
$z[1][4]['currentstyle']="<li><a href='~typelink~' rel=";
$z[1][4]['nofollow">~typename~</a></li> "']="";
$z[2]=Array("global","",488,520);
$z[2][4]=array();
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",996,1018);
$z[3][4]=array();
$z[3][4]['name']="cfg_tel";
$z[4]=Array("global","",1092,1118);
$z[4][4]=array();
$z[4][4]['name']="cfg_powerby";
$z[5]=Array("global","",1182,1206);
$z[5][4]=array();
$z[5][4]['name']="cfg_beian";

?>