<a  id="gift[field:id/]" class="gift2">
            <img src="/templets/default/img/gift[field:id/].png">
            <em>
                <span  id="g_name[field:id/]" >[field:name/]</span><br>
                <span class="bjprace[field:id/] bjprace"  >[field:price/]</span>元
                <span class="addps">[field:number_votes/]</span>票</em></a>
                <input type="hidden" name="s_id" id="s_id" value="[field:id/]">