<?php
$z[0]=Array("spaceurl","",24,42);
$z[0][4]=array();
$z[1]=Array("face","",71,84);
$z[1][4]=array();
$z[2]=Array("spaceurl","",154,172);
$z[2][4]=array();
$z[3]=Array("uname","",193,207);
$z[3][4]=array();
$z[4]=Array("spaceurl","",251,269);
$z[4][4]=array();
$z[5]=Array("spaceurl","",346,364);
$z[5][4]=array();
$z[6]=Array("spaceurl","",452,470);
$z[6][4]=array();
$z[7]=Array("rankname","",547,565);
$z[7][4]=array();
$z[8]=Array("jointime","",588,640);
$z[8][4]=array();
$z[8][4]['function']="MyDate('Y-m-d H:m',@me)";
$z[9]=Array("logintime","",663,716);
$z[9][4]=array();
$z[9][4]['function']="MyDate('Y-m-d H:m',@me)";

?>