<?php
$z[0]=Array("flink","",34,56);
$z[0][4]=array();
$z[0][4]['row']="24";
$z[1]=Array("channel","\r\n <li><a href=\"[field:typelink/]\" rel=\"nofollow\"> [field:typename/] </a></li>\r\n",178,298);
$z[1][4]=array();
$z[1][4]['type']="top";
$z[2]=Array("global","",491,523);
$z[2][4]=array();
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",1016,1038);
$z[3][4]=array();
$z[3][4]['name']="cfg_tel";
$z[4]=Array("global","",1040,1062);
$z[4][4]=array();
$z[4][4]['name']="cfg_tel";
$z[5]=Array("global","",1165,1191);
$z[5][4]=array();
$z[5][4]['name']="cfg_powerby";
$z[6]=Array("global","",1354,1378);
$z[6][4]=array();
$z[6][4]['name']="cfg_beian";

?>