$(function(){
	$("#gift1").click(function(){
	$(this).addClass("gift_on");
	$("#gift2,#gift3,#gift4,#gift5,#gift6,#gift7,#gift8,#gift9").removeClass("gift_on");
	$(".count_jg").css("display","block");
	$(".count_jg2,.count_jg3,.count_jg4,.count_jg5,.count_jg6,.count_jg7,.count_jg8,.count_jg9").css("display","none");
	})
	$("#gift2").click(function(){
	$(this).addClass("gift_on");
	$("#gift1,#gift3,#gift4,#gift5,#gift6,#gift7,#gift8,#gift9").removeClass("gift_on");
	$(".count_jg2").css("display","block");
	$(".count_jg,.count_jg3,.count_jg4,.count_jg5,.count_jg6,.count_jg7,.count_jg8,.count_jg9").css("display","none");
	})
	$("#gift3").click(function(){
	$(this).addClass("gift_on");
	$("#gift2,#gift1,#gift4,#gift5,#gift6,#gift7,#gift8,#gift9").removeClass("gift_on");
	$(".count_jg3").css("display","block");
	$(".count_jg2,.count_jg,.count_jg4,.count_jg5,.count_jg6,.count_jg7,.count_jg8,.count_jg9").css("display","none");
	})
	$("#gift4").click(function(){
	$(this).addClass("gift_on");
	$("#gift2,#gift3,#gift1,#gift5,#gift6,#gift7,#gift8,#gift9").removeClass("gift_on");
	$(".count_jg4").css("display","block");
	$(".count_jg2,.count_jg3,.count_jg,.count_jg5,.count_jg6,.count_jg7,.count_jg8,.count_jg9").css("display","none");
	})
	$("#gift5").click(function(){
	$(this).addClass("gift_on");
	$("#gift2,#gift3,#gift4,#gift1,#gift6,#gift7,#gift8,#gift9").removeClass("gift_on");
	$(".count_jg5").css("display","block");
	$(".count_jg2,.count_jg3,.count_jg4,.count_jg,.count_jg6,.count_jg7,.count_jg8,.count_jg9").css("display","none");
	})
	$("#gift6").click(function(){
	$(this).addClass("gift_on");
	$("#gift2,#gift3,#gift4,#gift5,#gift1,#gift7,#gift8,#gift9").removeClass("gift_on");
	$(".count_jg6").css("display","block");
	$(".count_jg2,.count_jg3,.count_jg4,.count_jg5,.count_jg,.count_jg7,.count_jg8,.count_jg9").css("display","none");
	})
	$("#gift7").click(function(){
	$(this).addClass("gift_on");
	$("#gift2,#gift3,#gift4,#gift5,#gift6,#gift1,#gift8,#gift9").removeClass("gift_on");
	$(".count_jg7").css("display","block");
	$(".count_jg2,.count_jg3,.count_jg4,.count_jg5,.count_jg6,.count_jg,.count_jg8,.count_jg9").css("display","none");
	})
	$("#gift8").click(function(){
	$(this).addClass("gift_on");
	$("#gift2,#gift3,#gift4,#gift5,#gift6,#gift7,#gift1,#gift9").removeClass("gift_on");
	$(".count_jg8").css("display","block");
	$(".count_jg2,.count_jg3,.count_jg4,.count_jg5,.count_jg6,.count_jg7,.count_jg,.count_jg9").css("display","none");
	})
	$("#gift9").click(function(){
	$(this).addClass("gift_on");
	$("#gift2,#gift3,#gift4,#gift5,#gift6,#gift7,#gift8,#gift1").removeClass("gift_on");
	$(".count_jg9").css("display","block");
	$(".count_jg2,.count_jg3,.count_jg4,.count_jg5,.count_jg6,.count_jg7,.count_jg8,.count_jg").css("display","none");
	})
})