<field:csz itemname="参赛者" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:csz>
<field:bmbh itemname="报名编号" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:bmbh>
<field:sfzhm itemname="身份证号码" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:sfzhm>
<field:lxdh itemname="联系电话" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:lxdh>
<field:email itemname="E-mail" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:email>
<field:sex itemname="性别" autofield="1" notsend="0" type="int" isnull="true" islist="1" default="女,男"  maxlength="250" page="">
</field:sex>
<field:hyzk itemname="婚姻状况" autofield="1" notsend="0" type="int" isnull="true" islist="1" default="已婚,未婚"  maxlength="250" page="">
</field:hyzk>
<field:zzmm itemname="政治面貌" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zzmm>
<field:gzdw itemname="工作单位" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:gzdw>
<field:yddh itemname="移动电话" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:yddh>
<field:photo itemname="上传照片" autofield="1" notsend="0" type="media" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:photo>
<field:mz itemname="民族" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:mz>
<field:s_province itemname="报名地址省" autofield="1" notsend="0" type="select" isnull="true" islist="1" default="北京市,天津市,上海市,重庆市,河北省,山西省,内蒙古,辽宁省,吉林省,黑龙江省,江苏省,浙江省,安徽省,福建省,江西省,山东省,河南省,湖北省,湖南省,广东省,广西,海南省,四川省,贵州省,云南省,西藏,陕西省,甘肃省,青海省,宁夏,新疆,香港,澳门,台湾省"  maxlength="250" page="">
</field:s_province>
<field:s_city itemname="报名地址市" autofield="1" notsend="0" type="int" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:s_city>
<field:s_county itemname="报名地址县" autofield="1" notsend="0" type="int" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:s_county>
<field:shipin itemname="视频" autofield="1" notsend="0" type="media" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:shipin>
<field:toupiao itemname="投票数" autofield="1" notsend="0" type="int" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:toupiao>
<field:caiyi itemname="才艺" autofield="1" notsend="0" type="textchar" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:caiyi>

<field:sh itemname="省会" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:sh>
