<?php
$z[0]=Array("csz","",19,60);
$z[0][4]=array();
$z[0][4]['function']="cn_substr(@me,10)";
$z[1]=Array("aid","",78,119);
$z[1][4]=array();
$z[1][4]['function']="cn_substr(@me,16)";
$z[2]=Array("s_province","",144,163);
$z[2][4]=array();
$z[3]=Array("caiyi","",183,226);
$z[3][4]=array();
$z[3][4]['function']="cn_substr(@me,12)";
$z[4]=Array("pubdate","",235,282);
$z[4][4]=array();
$z[4][4]['function']="MyDate('Y-m-d',@me)";

?>