<div class="tp_box"><span>[field:title/]</span><p><a href="[field:arcurl/]"><img src="[field:litpic/]" class="furen" alt="[field:title/]"><img src="/templets/default/img/tpfr.png" class="furenbg" alt="华夏夫人相框"></a></p><a href="">投票</a></div>
<table width='100%' border='0' cellspacing='1' cellpadding='1' id='voteitem'>
<form name='voteform' method='post' action='/plus/vote.php' target='_blank'>
<input type='hidden' name='dopost' value='send' />
<input type='hidden' name='aid' value='1' />
<input type='hidden' name='ismore' value='0' />
<tr align='center'><td height='30' id='votetitle' style='border-bottom:1px dashed #999999;color:#3F7652' ><strong>投票</strong></td></tr>
<tr><td height=30 bgcolor=#FFFFFF style='color:#666666'><input type='radio' name='voteitem' value='1' />12457</td></tr>
<tr><td height=30 bgcolor=#FFFFFF style='color:#666666'><input type='radio' name='voteitem' value='2' />258454</td></tr>
<tr><td height='30'>
<input type='submit' class='btn-1' name='vbt1' value='投票' />
<input type='button' class='btn-1' name='vbt2' value='查看结果' onClick=window.open('/plus/vote.php?dopost=view&aid=1'); /></td></tr>
</form>
</table>