<field:csz itemname="参赛者" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:csz>
<field:bmbh itemname="报名编号" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:bmbh>
<field:sh itemname="省会" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:sh>
<field:cy itemname="才艺" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:cy>

<field:sfzhm itemname="身份证号码" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:sfzhm>
<field:lxdh itemname="联系电话" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:lxdh>
<field:email itemname="E-mail" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:email>
<field:caiyi itemname="才艺" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:caiyi>
<field:sex itemname="性别" autofield="1" notsend="0" type="int" isnull="true" islist="1" default="女,男"  maxlength="250" page="">
</field:sex>
<field:hyzk itemname="婚姻状况" autofield="1" notsend="0" type="int" isnull="true" islist="1" default="已婚,未婚"  maxlength="250" page="">
</field:hyzk>
<field:zzmm itemname="政治面貌" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zzmm>
<field:gzdw itemname="工作单位" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:gzdw>
<field:yddh itemname="移动电话" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:yddh>
<field:s_province itemname="报名地址省" autofield="1" notsend="0" type="int" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:s_province>
<field:s_city itemname="报名地址市" autofield="1" notsend="0" type="int" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:s_city>
<field:s_county itemname="报名地址县" autofield="1" notsend="0" type="int" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:s_county>
<field:photo itemname="上传照片" autofield="1" notsend="0" type="media" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:photo>
<field:shipin itemname="上传视频" autofield="1" notsend="0" type="media" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:shipin>
<field:mz itemname="民族" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:mz>
