<?php
$z[0]=Array("global","",140,172);
$z[0][4]=array();
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",275,297);
$z[1][4]=array();
$z[1][4]['name']="cfg_tel";
$z[2]=Array("global","",353,380);
$z[2][4]=array();
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("channel","\r\n <li><a href=\"[field:typelink/]\"> [field:typename/] </a></li>\r\n",399,577);
$z[3][4]=array();
$z[3][4]['type']="top";
$z[3][4]['currentstyle']="<li><a href='~typelink~' class='on'>~typename~</a></li>";
$z[4]=Array("field","",702,724);
$z[4][4]=array();
$z[4][4]['name']="typename";
$z[5]=Array("global","",865,892);
$z[5][4]=array();
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("channel","\r\n <li><a href=\"[field:typelink/]\"> [field:typename/] </a></li>\r\n",912,1079);
$z[6][4]=array();
$z[6][4]['type']="top";
$z[6][4]['currentstyle']="<li><a href='~typelink~'>~typename~</a></li>";

?>