<?php
$typeArr[1] = '华夏夫人资讯';
$typeArr[2] = '华夏夫人报名';
$typeArr[3] = '投票注册';
$typeArr[4] = '培训系统';
$typeArr[5] = '招商加盟';
$typeArr[6] = '家教传承';
$typeArr[7] = '关于我们';
$typeArr[8] = '首页banner';
$typeArr[9] = '魅力夫人';
$typeArr[10] = '中国传统文化';
$typeArr[11] = '华夏夫人参选';
$typeArr[12] = '全国省市报名人数';
$typeArr[13] = '亲子无忧';
$typeArr[14] = '同缘梦教育';
$typeArr[15] = '同缘梦教育板块2';
$typeArr[16] = '在线投票';
$typeArr[18] = '在线报名';
$typeArr[21] = '活动资讯';
?>